import { sqliteTable, text, integer, primaryKey } from 'drizzle-orm/sqlite-core';

/* ------------------------------- Articles -------------------------------- */
// PK = (slug, locale): an article exists once per locale (DDL in
// lib/db/migrations.ts, kept in sync manually).

export const articles = sqliteTable('articles', {
  slug: text('slug').notNull(),
  locale: text('locale').notNull(), // en | fr | es | ar
  status: text('status', { enum: ['draft', 'published'] })
    .notNull()
    .default('published'),
  title: text('title').notNull().default(''),
  excerpt: text('excerpt').notNull().default(''),
  metaTitle: text('meta_title').notNull().default(''),
  metaDescription: text('meta_description').notNull().default(''),
  image: text('image').notNull().default(''),
  date: text('date').notNull().default(''),
  readingTime: text('reading_time').notNull().default(''),
  destination: text('destination'),
  widgetPartner: text('widget_partner'),
  widgetCity: text('widget_city'),
  widgetCountry: text('widget_country'),
  /** Raw MDX body (source of truth for article content) */
  body: text('body').notNull().default(''),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});

/* ------------------------------ Destinations ----------------------------- */
// PK = (slug, locale)

export const destinations = sqliteTable('destinations', {
  slug: text('slug').notNull(),
  locale: text('locale').notNull(),
  name: text('name').notNull().default(''),
  country: text('country').notNull().default(''),
  city: text('city').notNull().default(''),
  tagline: text('tagline').notNull().default(''),
  description: text('description').notNull().default(''),
  /** JSON string[] — e.g. ["Airport pick-up in minutes", "..."] */
  highlights: text('highlights').notNull().default('[]'),
  priceFrom: text('price_from').notNull().default(''),
  image: text('image').notNull().default(''),
  weight: integer('weight').notNull().default(99),
  active: integer('active', { mode: 'boolean' }).notNull().default(true),
});

/* -------------------------------- Partners ------------------------------- */
// PK = (id, locale)

export const partners = sqliteTable('partners', {
  id: text('id').notNull(), // rentalcars | autoeurope | economybookings
  locale: text('locale').notNull(),
  name: text('name').notNull().default(''),
  shortName: text('short_name').notNull().default(''),
  tagline: text('tagline').notNull().default(''),
  baseUrl: text('base_url').notNull().default(''),
  color: text('color').notNull().default('#1d4ed8'),
  commissionNote: text('commission_note').notNull().default(''),
  /** Real Travelpayouts widget snippet (HTML) for this partner + locale */
  embed: text('embed').notNull().default(''),
  active: integer('active', { mode: 'boolean' }).notNull().default(true),
  /** Optional per-partner Travelpayouts attribution override */
  marker: text('marker'),
  subId: text('sub_id'),
});

/* ------------------------------ Site settings ----------------------------- */
// key = 'site_url' | 'ga_id' | 'default_marker' | 'default_sub_id'
//      | 'affiliate_disclosure' | 'social_x' | 'social_instagram' | 'social_facebook'

export const siteSettings = sqliteTable('site_settings', {
  key: text('key').notNull(),
  value: text('value').notNull().default(''),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});

/* ----------------------------- Redirect links ----------------------------- */
// PK = slug (DDL in lib/db/migrations.ts)

export const redirectLinks = sqliteTable('redirect_links', {
  slug: text('slug').notNull(),
  /** Full destination URL (must start with http:// or https://) */
  destinationUrl: text('destination_url').notNull(),
  /** Optional partner id this link belongs to */
  partner: text('partner'),
  /** Internal note — never shown publicly */
  label: text('label').notNull().default(''),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  clickCount: integer('click_count').notNull().default(0),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});

/** One row per click event (analytics source of truth; click_count on
 * redirect_links stays as the denormalized fast counter). DDL in
 * lib/db/migrations.ts, kept in sync manually. */
export const redirectClicks = sqliteTable('redirect_clicks', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  /** FK → redirect_links.slug (that table's PK). */
  slug: text('slug').notNull(),
  /** Unix seconds UTC (drizzle mode 'timestamp'). */
  clickedAt: integer('clicked_at', { mode: 'timestamp' }).notNull(),
  /**
   * Per-click unique id generated by /go (crypto.randomUUID). Guarantees
   * at-most-once writes: the click is delivered via BOTH a fire-and-forget
   * keepalive fetch and an after() retry; any duplicate collides on the
   * unique index and is ignored, and only the insert that actually lands
   * increments the denormalized counter.
   */
  eventId: text('event_id'),
  /** SHA-256 of the client IP (peppered) — raw IPs are never stored. */
  ipHash: text('ip_hash'),
  /** ISO country code from Vercel geo headers (x-vercel-ip-country). */
  country: text('country'),
  city: text('city'),
  /** mobile | desktop | tablet (from UA parsing). */
  deviceType: text('device_type'),
  browser: text('browser'),
  os: text('os'),
  /** Site path (same-host) or host+path (external); null = direct. */
  referrer: text('referrer'),
  /** Site locale at click time (en | fr | es | ar). */
  locale: text('locale'),
  /** Bot/crawler traffic — kept in the table but excluded from headline stats. */
  isBot: integer('is_bot', { mode: 'boolean' }).notNull().default(false),
  userAgent: text('user_agent'),
});

/** Monthly aggregates for raw events older than the retention window. */
export const redirectClickRollups = sqliteTable(
  'redirect_click_rollups',
  {
    slug: text('slug').notNull(),
    /** 'YYYY-MM' (UTC month of clicked_at). */
    month: text('month').notNull(),
    /** Non-bot clicks archived in this month. */
    clicks: integer('clicks').notNull().default(0),
    botClicks: integer('bot_clicks').notNull().default(0),
  },
  (t) => ({ pk: primaryKey({ columns: [t.slug, t.month] }) })
);

/* --------------------------------- Types ---------------------------------- */

export type ArticleRow = typeof articles.$inferSelect;
export type NewArticleRow = typeof articles.$inferInsert;
export type DestinationRow = typeof destinations.$inferSelect;
export type NewDestinationRow = typeof destinations.$inferInsert;
export type PartnerRow = typeof partners.$inferSelect;
export type NewPartnerRow = typeof partners.$inferInsert;
export type SiteSettingRow = typeof siteSettings.$inferSelect;
export type RedirectLinkRow = typeof redirectLinks.$inferSelect;
export type NewRedirectLinkRow = typeof redirectLinks.$inferInsert;
export type RedirectClickRow = typeof redirectClicks.$inferSelect;
export type NewRedirectClickRow = typeof redirectClicks.$inferInsert;